services:
  # client:
  #   image: client
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   env_file: .env
  #   depends_on:
  #     - server

  server:
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stophis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    depends_on:
      - redis
    env_file: .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data: 