services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:80"
    env_file: .env
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stophis
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: server/Dockerfile
    command: python worker.py
    depends_on:
      - redis
    env_file: .env

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data: 